export const INCREMENT_CONUNTER = 'INCREMENT_CONUNTER'
export const DECREMENT_CONUNTER = 'DECREMENT_CONUNTER'
export const COUNTER_ACTION_STARTED = 'COUNTER_ACTION_STARTED'
export const COUNTER_ACTION_FINISHED = 'COUNTER_ACTION_FINISHED'
